# Generated by Django 4.1.7 on 2023-04-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquiry_Source', models.CharField(max_length=10)),
                ('Date_of_Birth', models.DateField()),
                ('Student', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=20)),
                ('Address', models.TextField(max_length=50)),
                ('Alternative_Email', models.CharField(max_length=20)),
                ('Alternative_Address', models.TextField(max_length=50)),
                ('Mobile', models.BigIntegerField()),
                ('Street', models.CharField(max_length=20)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('District', models.CharField(blank=True, max_length=20, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('Course', models.CharField(blank=True, max_length=20, null=True)),
                ('Pincode', models.CharField(max_length=20)),
                ('Whatsapp', models.CharField(max_length=20)),
                ('RollNo', models.CharField(max_length=20)),
                ('Registration_No', models.CharField(max_length=20)),
                ('College_Name', models.CharField(max_length=20)),
                ('Year_of_Pass', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_Name', models.CharField(max_length=20)),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=20)),
                ('Address1', models.CharField(blank=True, max_length=20, null=True)),
                ('Address2', models.CharField(blank=True, max_length=20, null=True)),
                ('Address3', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone', models.IntegerField(max_length=15)),
                ('E_mail', models.EmailField(blank=True, max_length=20, null=True)),
                ('Website', models.CharField(max_length=30)),
                ('Logo', models.ImageField(upload_to='images/')),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('Contact_Person', models.CharField(max_length=50)),
                ('Contact', models.IntegerField(max_length=50)),
                ('E_mail', models.EmailField(max_length=50)),
                ('Website', models.CharField(max_length=50)),
                ('Activate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.CharField(max_length=20)),
                ('Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='student_call_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Next_FollowUp_Date', models.DateTimeField()),
                ('Comment', models.CharField(max_length=200)),
                ('To_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addstudent.staff')),
                ('student_call_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addstudent.addstudent')),
            ],
        ),
        migrations.CreateModel(
            name='MapStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addstudent.batch')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addstudent.addstudent')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=20)),
                ('Active', models.BooleanField()),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addstudent.state')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(max_length=20, verbose_name='Branch')),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Street', models.CharField(blank=True, max_length=50, null=True)),
                ('Pincode', models.IntegerField(blank=True, max_length=10, null=True)),
                ('Mobile', models.IntegerField(max_length=13)),
                ('E_mail', models.EmailField(blank=True, max_length=20, null=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addstudent.district')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addstudent.state')),
            ],
        ),
    ]
